### ISSUE TITLE
modelsPath not found

### ISSUE THREAD

**Issue by Maykonn** [xpepermint/mongoose-glue#3]
My connection on index.js file:
```
var _ = require('mongoose-glue');
_.connect({
    // Path to a file where database connections are defined.
    configPath: 'config/mongoose.js',
    // Path to a directory with models files.
    modelsPath: 'models',
    // Custom logger function (set to `false` by default).
    logger: console.log
});
```

But I'm getting the following error:
```
module.js:340
    throw err;
    ^
Error: Cannot find module 'models/applications.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /var/www/server/node_modules/mongoose-glue/lib/models.js:111:18
    at Array.forEach (native)
    at loadModels (/var/www/server/node_modules/mongoose-glue/lib/models.js:106:28)
    at Object.module.exports.load (/var/www/server/node_modules/mongoose-glue/lib/models.js:164:7)
    at Object.module.exports.connect (/var/www/server/node_modules/mongoose-glue/lib/index.js:47:12)
    at Object.<anonymous> (/var/www/server/server.js:8:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

I try change the modelsPath param to: modelsPath: './models' but not works too.
What's happen?
Thanks!

**Comment by Maykonn** [comment]
I solve using proccess.cwd();
But now I'm getting this error:

```
TypeError: Cannot call method 'model' of null
```

My Model:
```
// Dependencies
var mongoose = require('mongoose');
var _ = require('mongoose-glue');

// Schema
var ApplicationSchema = new mongoose.Schema({
    name: String,
    email: String,
    status: String
});

ApplicationSchema.connection = 'my_db_name';
module.exports = mongoose.model('Application', ApplicationSchema);
```

What's happen? Thanks!

**Comment by Maykonn** [comment]
Well, just make like /examples, don't use mongoose.model.
